### ISSUE TITLE
missing dependencies in build documentation

### ISSUE THREAD

**Issue by tofke** [linuxpaycoin/linuxpay#1]
Hello linuxpay team,

This page missed a developpement library as a required dependency to build a full wallet on Linux : 
https://github.com/linuxpaycoin/linuxpay/blob/master/doc/build-unix.md

### Describe the issue
When builing an error says "libevent not found", altough libevent was installed.
After comparing with other nodes where i build some other coins, i found that the missing package was "libevent-dev". So after issuing "sudo apt install libevent-dev", the build process was going fine.

#### If so, please list the steps to reproduce below:
1. Install a fresh Ubuntu 16.04 and follow the build-unix.md guide
2. See the error about the missing component ... 

### Expected behavior
Build should not produce such an error.

### Actual behavior
When builing an error says "libevent not found", altough libevent was installed.

### What version of Linuxpay Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS: Ubuntu 16.04
- CPU: x86_64
- RAM: 4G
- Disk size: 1 To
- Disk Type (HD/SDD): HDD

### Any extra information that might be useful in the debugging process.
I paste here just the last two line of "./configure" output : 
checking for EVENT... no
configure: error: libevent not found.

**Comment by linuxpaycoin** [comment]
If you're trying to build software then you need the development package. Install libevent-devel.
For ubuntu based distributions the package is libevent-dev

Install this as follows....

> wget http://monkey.org/~provos/libevent-1.4.14b-stable.tar.gz
> tar xzf libevent-1.4.14b-stable.tar.gz
> cd libevent-1.4.14b-stable
> ./configure --prefix=/opt/libevent

# hopefully, you haven't encountered any errors so far

>  make
>  make install

You should have libevent installed in /opt/libevent. To make sure:

> ls -la /opt/libevent
